# Generated by Django 6.1.1 on 2026-09-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_at_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece(s)'), ('kg', 'Kg(s)')], default='piece', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece(s)'), ('kg', 'Kg(s)')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
