# Generated by Django 6.1.1 on 2026-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cartitem_unit_orderitem_unit_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight_at_order',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
