# Generated by Django 6.1.1 on 2026-09-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per kilogram (for kg or both options)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Per Piece (pc)'), ('kg', 'Per Kilogram (kg)'), ('both', 'Both (Piece & Kg)')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per piece, or base price', max_digits=8),
        ),
    ]
