# Generated by Django 6.1.1 on 2026-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_per_kg_product_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, default='', help_text='Weight or piece description (e.g. 1 kg, 500g, 6 pcs, 1 piece)', max_length=50),
        ),
    ]
