# Generated by Django 6.1.1 on 2026-09-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_per_kg',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Total price for this item', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='piece', max_length=10),
        ),
    ]
